### PR TITLE
Fea adjust condensed medium

### PR DESCRIPTION
**Pull request by cjdunn**
-updated Roboto-min.designspace to include Condensed Medium and Condensed Medium Italic instances
-added filename values to instances in designspace so individual instances can be generated via fontmake if needed
-rebuilt var font and added to /fonts folder

### CODE REVIEW

**Comment by cjdunn** [comment]
I made a small change:  update designspace to remove underscores in "filename" value so output filenames matches previous Roboto instances

**Comment by cjdunn** [comment]
@davelab6 thanks for approving, please feel free to merge into master and delete this branch. Or if you'd like me to do so just let me know, thanks.

**Comment by davelab6** [comment]
Done and done - but this is a TN repo after all :)

Marc has proposed moving this project into the official one, but I need to chat with some other Google staff about that before proceeeding :)

**Comment by cjdunn** [comment]
@davelab6 thanks, I just try to avoid merging my own pull requests as I have been told it's best practices for a different person to do the merge. Maybe it's not absolutely necessary, but I find it to be a nice confirmation. Cheers!

**Comment by m4rc1e** [comment]
@cjdunn Condensed Medium instances haven't been added to https://github.com/TypeNetwork/Roboto/blob/master/Scripts/writeDesignSpace-min.py 
Could you add them please?

**Comment by davelab6** [comment]
CJ, yes always good to get a 2nd pair of eyes on things; at G it is
actually impossible to submit a PR yourself ;) Happy to do it but please
ask me or Marc to do it when needed :)

MF, good catch!

**Comment by cjdunn** [comment]
@davelab6 @m4rc1e Sure thing! 

I made a branch with these updates called fea-update-build-script and here's my pull request:
https://github.com/TypeNetwork/Roboto/pull/23

I don't know why it can't merge automatically. I only changed 2 files which are: 
writeDesignSpace-min.py
Roboto-min.designspace

Do either of you know why this is happening? All that's different is a new attribute added to the designspacefile, not sure why Git would have a problem with this. Any ideas?

**Pull request merged**
