### PR TITLE
[Compare] added master_ttf vs v2.138 comparisons

### PR DESCRIPTION
**Pull request by m4rc1e**
As mentioned in #16, I thought it wise to diff the static fonts first.

It may be easier to view the images and reports directly in GH, https://github.com/m4rc1e/Roboto-1/tree/testing/Docs/Compare/master_ttf_vs_v2_138

I'm submitting this as a PR because it contains images and reports which may be of use in the future.

@anthrotype @davelab6 have a quick look at the reports in this PR. Imo, I'm fairly happy with the outcome. The only thing I question are the distorted glyphs. If we're all happy, I'll finish off the stated TODO tasks.

I'm also curious how we should version this font? Imo, I'd like this to be distinguishable from the official release for the time being. Some bugs have been fixed in the VF which haven't been done in the official release yet. When we merge both repos and fix the regressions, then they can both have the same version number.

### TODO (M Foley)
- Bump version number
- Push harder for slant axis css fix (italic testing on VFs is currently broken)
- ~~Determine whether caretSlopeRun and caretSlopeRise are wrong then fix~~
- Add Condensed Medium and Condensed Medium Italic instances (currently testing this, #17)

### CODE REVIEW

**Comment by m4rc1e** [comment]
Just had a quick chat to Cosimo. The missing mkmks reports are misleading.

It seems that if a designer tries to mkmk position a combining glyph e.g acutecomb against a non combining glyph e.g ogonek, it won't shape.

```
Marc:~ marc$ hb-shape /Users/marc/Documents/googlefonts/manual_font_cleaning/_privates/Roboto/master_ttf/Roboto-Regular.ttf  ̯¸ --features=+mark,+mkmk
[breveinvsubnosp=0+0|cedilla=1+508]
```

I'll make sure diffenator ignores these combos, even if they exist in the font.

screen shot 2018-07-12 at 16 16 53
*Above anchor combo in v2.138 Roboto*

**Comment by davelab6** [comment]
I seem to recall that macOS will do "off spec" joining, based on
proprietary character positioning info in its shaping engine, which is
maybe where you saw this happening.

**Comment by m4rc1e** [comment]
CaretSlop run/rise is being set by ufo2ft, https://github.com/googlei18n/ufo2ft/commit/5d2b23c009c3eb956a56ce54c73ad864dba31355#diff-8cbeaeba57ab2a0082649c81b768ab2bR82. According to the [Ms spec](https://docs.microsoft.com/en-us/typography/opentype/spec/hhea), the new values seem correct. The old values were the same for both Roman and Italic fonts which is incorrect.

@anthrotype I've found no way to properly test this. I've tried Mac pages and a lot of Win browsers and had no joy. Do you know of any apps which use the hhea.caretSlopeRun and hhea.caretSlope?

**Comment by anthrotype** [comment]
I think, but I'm not sure, that MS Word uses the caret slope in hhea. Maybe @moyogo knows

**Comment by m4rc1e** [comment]
Both cursors slant in Ms Word,

screen shot 2018-07-17 at 14 54 05
*Roboto VF*

screen shot 2018-07-17 at 15 00 48
*Roboto v2.138 unhinted*


I'm tempted to just leave this since the values now conform to the spec.

**Comment by davelab6** [comment]
Values on spec is good :)

**Comment by davelab6** [comment]
@m4rc1e what is needed to merge this?

**Comment by m4rc1e** [comment]
Nothing. We can merge.

**Pull request merged**
