### PR TITLE
Build v3

### PR DESCRIPTION
**Pull request by m4rc1e**
This PR includes the following:

- Builds for ChromeOS, Android, Web, Unhinted, Hinted
- CI/CD using github actions
- Scripts to build VTT sources
- v2 font unit tests ported to custom fontbakery profiles
- Metadata fixes to ensure there are minimal regressions when compared against v2.136

Keep this open, I'm still tidying,.

### CODE REVIEW

**Comment by m4rc1e** [comment]
@sannorozco I'm done.

Please feel free to review it. Our aim is to transfer this repo to https://github.com/googlefonts/roboto once we're all happy.

**Comment by davelab6** [comment]
@sannorozco  I am surprised to see this merged when the CI is showing a red 'x' (failed) for the latest commit. 

Screen Shot 2020-06-17 at 12 33 47 PM

**Comment by sannorozco** [comment]
@davelab6 I saw the CI red ‘x’, and checked, it was only one error, not ‘All checks have failed’, by one line of code added by Marc, that I was about to tell, I figured we can merge again with another PR, but I was rushing to merge. Sorry, won’t happen again.

**Comment by sannorozco** [comment]
@m4rc1e, I was rushing to merge and saw one CI error, latest commit in “test fonts”. should be quick right?

Screen Shot 2020-06-17 at 12 09 07 PM

**Comment by m4rc1e** [comment]
No problem, I'll push a fix soon and then tag a release. Thanks.

**Pull request merged**
